#!/bin/bash
# GITHUB_PAT -- environment variable from systemd service file
#
set -e

HTTPS_URL="https://x-oauth-basic:$GITHUB_PAT@github.com/billpittman/ssh_ca.git"

[ -z "$GITHUB_PAT" ] && echo "Github personal access token missing." && exit 1

# perform update
git pull "$HTTPS_URL" main 2>/dev/null
